name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:18
    services:
      redis:
        image: redis
    steps:
      - uses: actions/checkout@v3
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn test
